import Head from "next/head"
import Image from "next/image"
import Link from "next/link"

import Banner from "../../components/banner"

import styles from "@/styles/Home.module.css"

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("Hi banner Button")
  }

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
      </main>
    </>
  )
}
